# TrajectoryPlannerROS:
#   acc_lim_x: 2.5
#   acc_lim_y: 0
#   acc_lim_theta: 3.2
#
#   max_vel_x: 0.6
#   min_vel_x: 0.6
#   min_vel_theta: -1.0
#   max_vel_theta: 1.0
#   min_in_place_vel_theta: 1.0
#   escape_vel: -0.8
#   holonomic_robot: false
#
#   yaw_goal_tolerance: 0.5
#   xy_goal_tolerance: 0.1
#   latch_xy_goal_tolerance: true #false
#
#   # meter_scoring: true

TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_theta: 3.2

  max_vel_x: 0.6
  min_vel_x: 0.6
  max_vel_theta: 1.0
  # min_vel_theta: -1.0
  min_in_place_vel_theta: 0.1
  # escape_vel: -0.8


  holonomic_robot: false


  # yaw_goal_tolerance: 0.5
  # xy_goal_tolerance: 0.1

  meter_scoring: true
