TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.6
  min_vel_theta: 1.39372549
  max_vel_theta: 3.14
  min_in_place_vel_theta: 1.39372549

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0

  holonomic_robot: true
  meter_scoring: true
