TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_theta: 3.2
  max_vel_x: 0.2
  min_vel_x: 0.2
  min_vel_theta: -1.39372549
  max_vel_theta: 1.39372549
  min_in_place_vel_theta: 0.5
  escape_vel: -0.1
  holonomic_robot: false

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.50
  latch_xy_goal_tolerance: true #false

  # meter_scoring: true
