local_costmap:
  global_frame: /map
  robot_base_frame: odom
  update_frequency: 1.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.1
  transform_tolerance: 1.0
