local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  transform_tolerance: 1.0
  update_frequency: 1.0
  publish_frequency: 1.0
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.1


  static_map: false
